# Generated by Django 3.0.3 on 2020-07-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professional_Resources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Field', models.CharField(max_length=50)),
                ('Author', models.CharField(max_length=50)),
                ('Descrpition', models.CharField(max_length=300)),
                ('Url', models.URLField(max_length=264)),
                ('Type', models.CharField(max_length=20)),
                ('Self_Email', models.EmailField(max_length=100)),
                ('Price', models.IntegerField()),
                ('Released_On', models.DateField()),
            ],
        ),
    ]
