# Generated by Django 3.0.3 on 2020-07-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal_Development_Resources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Author', models.CharField(max_length=25)),
                ('Name_Of_Resource', models.CharField(max_length=100)),
                ('Url', models.URLField(max_length=150)),
                ('Type', models.CharField(max_length=25)),
                ('Self_Email', models.EmailField(max_length=100)),
                ('Price', models.IntegerField()),
                ('Released_On', models.DateField()),
            ],
        ),
    ]
