# Generated by Django 3.0.3 on 2020-07-31 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0006_auto_20200730_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Name', models.CharField(max_length=50)),
                ('Role', models.CharField(max_length=50)),
                ('Company', models.CharField(max_length=50)),
                ('field', models.CharField(max_length=50)),
                ('Target_Section', models.CharField(max_length=25)),
                ('AdviceforGoalAttainment', models.TextField()),
                ('SelfExperience', models.TextField()),
                ('Paths', models.TextField()),
                ('ResourcesUsed', models.TextField()),
            ],
        ),
    ]
