# Generated by Django 3.0.3 on 2020-08-01 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0007_addexperience'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetAJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Field', models.CharField(max_length=40)),
                ('Experience', models.CharField(max_length=40)),
                ('Subject', models.CharField(max_length=50)),
                ('Source', models.CharField(max_length=50)),
                ('Url', models.URLField()),
            ],
        ),
    ]
