# Generated by Django 3.0.3 on 2020-08-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0008_getajob'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentsandSuggestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('Comments', models.TextField()),
                ('Suggestions', models.TextField()),
                ('Date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='professional_resources',
            name='Descrpition',
            field=models.TextField(),
        ),
    ]
