# Generated by Django 3.0.3 on 2020-08-04 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0009_auto_20200802_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentsandsuggestions',
            name='Date',
        ),
    ]
