# Generated by Django 3.0.3 on 2020-08-04 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0010_remove_commentsandsuggestions_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge2',
            name='Start_Date',
        ),
    ]
