# Generated by Django 3.0.3 on 2020-08-04 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0011_remove_challenge2_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mygoal',
            old_name='Goal_Url',
            new_name='Subject_Url',
        ),
    ]
