# Generated by Django 3.0.3 on 2020-08-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0012_auto_20200804_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional_resources',
            name='Target_Audience',
            field=models.CharField(choices=[('College Students', 'College Students'), ('0-2 yrs', '0-2 yrs'), ('2-5 yrs', '2-5 yrs'), ('5-10 yrs', '5-10 yrs'), ('10-15 yrs', '10-15 yrs'), ('15-20 yrs', '15-20 yrs')], default='College Students', max_length=20),
            preserve_default=False,
        ),
    ]
