# Generated by Django 3.0.3 on 2020-08-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0013_professional_resources_target_audience'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GetAJob',
        ),
        migrations.RenameField(
            model_name='professional_resources',
            old_name='Descrpition',
            new_name='Description',
        ),
        migrations.AlterField(
            model_name='professional_resources',
            name='Target_Audience',
            field=models.CharField(choices=[('College Students', 'College Students'), ('0-2 yrs experience', '0-2 yrs experience'), ('2-5 yrs experience', '2-5 yrs experience'), ('5-10 yrs experience', '5-10 yrs experience'), ('10-15 yrs experience', '10-15 yrs experience'), ('15-20 yrs experience', '15-20 yrs experience')], max_length=20),
        ),
    ]
