# Generated by Django 3.0.3 on 2020-08-21 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0014_auto_20200816_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='mylibrary',
            name='Price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
