# Generated by Django 3.0.3 on 2020-08-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0015_mylibrary_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addexperience',
            name='Target_Section',
            field=models.CharField(choices=[('College Students', 'College Students'), ('0-2 yrs experience', '0-2 yrs experience'), ('2-5 yrs experience', '2-5 yrs experience'), ('5-10 yrs experience', '5-10 yrs experience'), ('10-15 yrs experience', '10-15 yrs experience'), ('15-20 yrs experience', '15-20 yrs experience')], max_length=25),
        ),
    ]
