# Generated by Django 3.0.3 on 2020-08-29 12:16

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0017_auto_20200829_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_development_resources',
            name='Released_On',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='professional_resources',
            name='Released_On',
            field=models.DateField(default=datetime.date(2020, 8, 29)),
            preserve_default=False,
        ),
    ]
