# Generated by Django 3.0.3 on 2020-10-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0018_auto_20200829_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Field', models.CharField(max_length=50)),
                ('Author', models.CharField(max_length=50)),
                ('Description', models.TextField()),
                ('Url', models.URLField(max_length=264)),
                ('Target_Audience', models.CharField(choices=[('College Students', 'College Students'), ('0-2 yrs experience', '0-2 yrs experience'), ('2-5 yrs experience', '2-5 yrs experience'), ('5-10 yrs experience', '5-10 yrs experience'), ('10-15 yrs experience', '10-15 yrs experience'), ('15-20 yrs experience', '15-20 yrs experience')], max_length=20)),
                ('Type', models.CharField(max_length=20)),
                ('Self_Email', models.EmailField(max_length=100)),
                ('Released_On', models.DateField()),
            ],
        ),
    ]
