# Generated by Django 3.0.3 on 2020-10-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0019_advice'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPortal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_of_portal', models.CharField(max_length=50)),
                ('URL', models.URLField(max_length=264)),
            ],
        ),
    ]
